Añado texto inservible
lentes4k/Proyecto-IV pull request #1
Opened 2021-09-16 09:24 UTC by lentes4k

2021-09-17 15:37 UTC, JJ requested changes
Porfa, dale una vueltecilla a ver qué tal.

2021-09-17 15:37 UTC, JJ commented on README.md
>  Una bacanería de proyecto para la asignatura de IV
Conviene que especifiques un poco más qué es lo que quieres resolver. También tenías que haber hecho todo el cambio en esta rama.

2021-09-17 16:09 UTC, lentes4k commented on README.md
>  Una bacanería de proyecto para la asignatura de IV
¿Con especificar más te refieres a la idea del problema? Y con todo el cambio en la rama no entiendo a que te refieres profesor

2021-09-17 18:07 UTC, JJ commented on README.md
>  Una bacanería de proyecto para la asignatura de IV
Sí, claro, es lo que pide el guión del objetivo. Si miras los cambios en este PR, has hecho todos los cambios en main, y lo único que has cambiado en esta rama es la última frase. Reescribe todo el README (menos posiblemente el título) y pon la idea sobre la que desarrollarás el proyecto.

2021-09-18 09:33 UTC, lentes4k commented on README.md
>  Una bacanería de proyecto para la asignatura de IV
Okey, el texto lo añadí al crear el repositorio, y para poder hacer el PR hice ese pequeño cambio. No he desarrollado aún del todo la idea en mi cabeza, en cuanto la tenga la añado. Muchas gracias! :blush:

2021-09-19 15:03 UTC, merged