Hago las cositas del Objetivo 1
lentes4k/Proyecto-IV pull request #12
Opened 2021-09-25 17:07 UTC by lentes4k

2021-09-26 07:22 UTC, JJ reviewed
En la descripción inicial hay un potencial para una aplicación con una lógica de negocio adecuada, pero para que lo alcances tienes que desligar el procesamiento de la información y la información en sí de cualquier tipo de implementación (las repetidas referencias a "el chat"). Para empezar, si lo que vas a tratar es con Telegram no tiene ningún sentido que hagas una aplicación en el servidor. Implementarías un proxy transparente en tu propio sistema por el que pasarían todos los mensajes. Y los demás temas de implementación serían, por decirlo suavemente, complejos. Tendrías que interpretar también tus propios mensajes, con los comandos que quieras, etcétera. Todo ello no se puede (ni para el caso debe) implementarse en la nube, ni el que estén tan ligados a la implementación ayuda al diseño de la aplicación. Los usuarios por tanto van ligados a este tipo de implementación (usuario casual, usuario no sé qué) y no tienen nada que ver con la resolución del problema.
Debes hacer lo siguiente:
1. Abstraer el problema de forma que puedas comenzar el proyecto sin tener en cuenta ningún tipo de implementación.
2. Reescribir la descripción del problema (y la posible solución) desacoplándolo de cualquier posible implementación.
3. Hacer casos de uso que realmente no tengan como mejor implementación algo en el ordenador del cliente. Cualquier cosa ligada a mensajería personal va a tener una implementación en el ordenador personal.
Por supuesto, una vez hecho eso deberás releer el material que tengas (clase, vídeos) sobre qué constituye un milestone, es decir, un producto mínimamente viable.

2021-09-26 07:22 UTC, JJ commented on docs/usuarios.md
> +**Historias de usuario relaciondas ->** [HU1](https://github.com/lentes4k/Proyecto-IV/issues/4), [HU2](https://github.com/lentes4k/Proyecto-IV/issues/5), [HU3](https://github.com/lentes4k/Proyecto-IV
Por favor, usa la chuleta de Markdown que os di para formatear esto mejor.
Por otro lado, los perfiles de usuario tienen que estar más relacionados con las intenciones y capacidades cognitivas que con lo que pueda hacer o no. (Y no tengo muy claro qué es "el chat")

2021-09-26 07:22 UTC, JJ commented on docs/usuarios.md
> +
Las historias de usuario son previas a la decisión sobre el tipo de aplicación, están en el dominio del problema. No tienen ninguna relación con la implementación.

2021-09-26 07:22 UTC, JJ commented on docs/usuarios.md
> +### Usuario potencial
De veras, llegado a este punto no tengo ni idea de qué se está hablando ni veo la relación con el problema.

2021-09-26 13:11 UTC, lentes4k commented
He modificado un poco el archivo en doc. He sustituido chat por bot, mi intención al hablar de chat es el cajón de texto de Telegram con el que se interactúa con el bot (y con el resto de usuarios en lo referido al uso normal de Telegram)
Por otra parte he modificado los milestone para que representen realmente PMV (uno sería la gestión en si de notas, otro la posibilidad de obtener datos curiosos, otro para ver estadísticas) que, bajo mi punto de vista presentan el producto principal y diferentes productos añadidos para hacer el concepto más interesante.
Ya me vas comentando si me falta algo o sigo sin entender algún concepto.

2021-09-26 15:42 UTC, JJ commented
> He modificado un poco el archivo en doc. He sustituido chat por bot, mi intención al hablar de chat es el cajón de texto de Telegram con el que se interactúa con el bot (y con el resto de usuarios en lo referido al uso normal de Telegram)
> Por otra parte he modificado los milestone para que representen realmente PMV (uno sería la gestión en si de notas, otro la posibilidad de obtener datos curiosos, otro para ver estadísticas) que, bajo mi punto de vista presentan el producto principal y diferentes productos añadidos para hacer el concepto más interesante.
> Ya me vas comentando si me falta algo o sigo sin entender algún concepto.

"Gestión de las notas" no es un producto. ¿Qué es gestión? ¿Qué son las notas? ¿Qué necesitas para gestionar las notas? ¿Una aplicación cliente servidor? ¿Qué será primero? ¿El cliente o el servidor?
Por favor, revisa el concepto de "producto mínimamente viable" y el de "hito", que tiene que ser un paso en la producción de un producto que incluya un producto.

2021-09-26 16:17 UTC, lentes4k commented
> > He modificado un poco el archivo en doc. He sustituido chat por bot, mi intención al hablar de chat es el cajón de texto de Telegram con el que se interactúa con el bot (y con el resto de usuarios en lo referido al uso normal de Telegram)
> > Por otra parte he modificado los milestone para que representen realmente PMV (uno sería la gestión en si de notas, otro la posibilidad de obtener datos curiosos, otro para ver estadísticas) que, bajo mi punto de vista presentan el producto principal y diferentes productos añadidos para hacer el concepto más interesante.
> > Ya me vas comentando si me falta algo o sigo sin entender algún concepto.
> 
> "Gestión de las notas" no es un producto. ¿Qué es gestión? ¿Qué son las notas? ¿Qué necesitas para gestionar las notas? ¿Una aplicación cliente servidor? ¿Qué será primero? ¿El cliente o el servidor?
> Por favor, revisa el concepto de "producto mínimamente viable" y el de "hito", que tiene que ser un paso en la producción de un producto que incluya un producto.

Es que bajo mi punto de vista. El centro de la aplicación es la gestión de las notas (escribirlas, almacenarlas...) por lo tanto el PMV básico sería eso mismo. Las demás cosas (datos curiosos, estadísiticas...) serían otros "productos" (o funciones) que añaden valor al bot y que dotarían de más "prestigio" a la función principal, que sin desviarnos, sigue siendo la de almacenar las notas

2021-09-26 16:27 UTC, JJ commented
Creo que ya lo he dicho. Almacenar y recuperar no es lógica de negocio. "Gestión" tampoco describe un producto. Tienes que describir qué va a ser el producto. Generalmente el primer hito va a incluir la lógica de negocio en una forma que compile y provea funcionalidad básica. Por favor, entiende bien qué es cada cosa y cámbialo para poder alcanzar el objetivo.

2021-09-26 16:29 UTC, JJ commented
Por si no ha quedado claro, un "bot" es un cliente. No se despliega en la nube. Que hables de bots en vez de chats no cambia nada. Te he explicado arriba cómo puedes describir el problema y la posible solución sin ningún tipo de referencia a implementación, en la nube o fuera de ella. Por favor, revísalo, así como el concepto de "lógica de negocio" y "producto mínimamenbe viable"

2021-09-26 16:56 UTC, lentes4k commented
Entonces en vez de explicar lo que es el bot en el lado del cliente (es decir, lo que ofrece al usuario) debo de explicar lo que es el bot en cuánto a procesamiento? Por ejemplo, explicar cómo llevaría a cabo el almacenamiento de notas. 
Es que no veo claro el por qué, ofrecer como PMV la creación de cajones, el almacenamiento de notas, el procesamiento de las notas por medio del bot, entre otras cosas que yo englobo en mi "sistema de gestión de notas" no es correcto.
Me pongo en el lugar de un usuario, y el poder crear las notas, almacenarnas (ya sea explícitamente o mediante proceso automático), recuperarlas y el manejo de los, por mí llamados, cajones (una suerte de carpetas) ya sería una funcionalidad básica

2021-09-26 18:11 UTC, JJ commented
> Entonces en vez de explicar lo que es el bot en el lado del cliente (es decir, lo que ofrece al usuario) debo de explicar lo que es el bot en cuánto a procesamiento? Por ejemplo, explicar cómo llevaría a cabo el almacenamiento de notas.

Almacenamiento de notas no es una lógica de negocio. Por favor, consulta el minitaller sobre el tema.

> Es que no veo claro el por qué, ofrecer como PMV la creación de cajones, el almacenamiento de notas, el procesamiento de las notas por medio del bot, entre otras cosas que yo englobo en mi "sistema de gestión de notas" no es correcto.

Porque un producto tiene que ser un producto. No una descripción de cosas que hace no se sabe muy bien qué.

> Me pongo en el lugar de un usuario, y el poder crear las notas, almacenarnas (ya sea explícitamente o mediante proceso automático), recuperarlas y el manejo de los, por mí llamados, cajones (una suerte de carpetas) ya sería una funcionalidad básica

En esta asignatura no vamos a construir interfaz de usuario. Para llegar a un punto en que el usuario tenga que pedir cosas, ¿tendrá que haber alguna lógica de negocio ya programada para recibir esas peticiones?

2021-09-26 18:19 UTC, lentes4k commented
> > Entonces en vez de explicar lo que es el bot en el lado del cliente (es decir, lo que ofrece al usuario) debo de explicar lo que es el bot en cuánto a procesamiento? Por ejemplo, explicar cómo llevaría a cabo el almacenamiento de notas.
> 
> Almacenamiento de notas no es una lógica de negocio. Por favor, consulta el minitaller sobre el tema.
> 
> > Es que no veo claro el por qué, ofrecer como PMV la creación de cajones, el almacenamiento de notas, el procesamiento de las notas por medio del bot, entre otras cosas que yo englobo en mi "sistema de gestión de notas" no es correcto.
> 
> Porque un producto tiene que ser un producto. No una descripción de cosas que hace no se sabe muy bien qué.
> 
> > Me pongo en el lugar de un usuario, y el poder crear las notas, almacenarnas (ya sea explícitamente o mediante proceso automático), recuperarlas y el manejo de los, por mí llamados, cajones (una suerte de carpetas) ya sería una funcionalidad básica
> 
> En esta asignatura no vamos a construir interfaz de usuario. Para llegar a un punto en que el usuario tenga que pedir cosas, ¿tendrá que haber alguna lógica de negocio ya programada para recibir esas peticiones?

Entonces creo que puedo sacar poca chicha y tendré que cambiar de idea. No veo cómo aportar lógica de negocio en esta.

2021-09-26 18:30 UTC, JJ commented
> > > Entonces en vez de explicar lo que es el bot en el lado del cliente (es decir, lo que ofrece al usuario) debo de explicar lo que es el bot en cuánto a procesamiento? Por ejemplo, explicar cómo llevaría a cabo el almacenamiento de notas.
> > 
> > 
> > Almacenamiento de notas no es una lógica de negocio. Por favor, consulta el minitaller sobre el tema.
> > > Es que no veo claro el por qué, ofrecer como PMV la creación de cajones, el almacenamiento de notas, el procesamiento de las notas por medio del bot, entre otras cosas que yo englobo en mi "sistema de gestión de notas" no es correcto.
> > 
> > 
> > Porque un producto tiene que ser un producto. No una descripción de cosas que hace no se sabe muy bien qué.
> > > Me pongo en el lugar de un usuario, y el poder crear las notas, almacenarnas (ya sea explícitamente o mediante proceso automático), recuperarlas y el manejo de los, por mí llamados, cajones (una suerte de carpetas) ya sería una funcionalidad básica
> > 
> > 
> > En esta asignatura no vamos a construir interfaz de usuario. Para llegar a un punto en que el usuario tenga que pedir cosas, ¿tendrá que haber alguna lógica de negocio ya programada para recibir esas peticiones?
> 
> Entonces creo que puedo sacar poca chicha y tendré que cambiar de idea. No veo cómo aportar lógica de negocio en esta.

¿Quién dijo miedo? Mira todo lo que se me ocurre con la idea básica de "clasificar texto"
1. Clasificación del texto basado en un análisis del mismo.
2. Clasificación según herramientas de análisis de texto (hay por ejemplo que clasifican la "adultez" de un texto basados en la longitud de palabras y frases)
3. Clasificación de texto usando TFIDF y clustering del mismo
4. Nubes de palabras

Con texto se pueden hacer un montón de cosas. ¿No habéis dado nada de eso en ninguna asignatura?

2021-09-27 08:44 UTC, lentes4k commented
En ese caso podría basar la aplicación en la clasificación automática de las notas y el conteo de palabras y otras estadísticas?
En ese caso es básicamente lo que trato de exponer con las HUs e hitos pero con otras funciones de almacenar/guardar además.
No se si es que no estoy entendiendo bien los conceptos entonces

2021-09-27 16:54 UTC, JJ commented
> En ese caso podría basar la aplicación en la clasificación automática de las notas y el conteo de palabras y otras estadísticas?

Siempre que resuelvan un problema. Ya os dije que una de las fases del diseño de un aplicación es empatizar. Trata de pensar qué usuario podía interesarle una y otra cosa y de qué forma se podría hacer la clasificacion automática.

> En ese caso es básicamente lo que trato de exponer con las HUs e hitos pero con otras funciones de almacenar/guardar además.
> No se si es que no estoy entendiendo bien los conceptos entonces

Es posible. Te agradecería que le dieras una vuelta.

2021-09-28 14:56 UTC, lentes4k commented
Profe, le he dado una vueltecilla a todo

2021-09-28 15:25 UTC, JJ requested changes
Por favor, trata de pensar en esto como una aplicación real que alguien (tú u otra persona) tendrá que desarrollar. Los hitos son las diferentes etapas por las que tiene que pasar. Las HUs son lo que esa persona tendría que hacer. Tomemos #4. ¿Crees que más allá de poner una clase "cajones" con una función para crearlos, va a poder hacer algo más? Mira el hito en el que está incluida, un "sistema". Si te entrega una web que tiene un formulario que dice "nombre de cajón" y al meter algo te dice "creado cajón" ¿se alcanzará ese producto? Por favor, no os quedéis con la letra de lo que escribís. Tratad de entender la música (los conceptos que hay detrás).

2021-09-28 15:40 UTC, lentes4k commented
> Por favor, trata de pensar en esto como una aplicación real que alguien (tú u otra persona) tendrá que desarrollar. Los hitos son las diferentes etapas por las que tiene que pasar. Las HUs son lo que esa persona tendría que hacer. Tomemos #4. ¿Crees que más allá de poner una clase "cajones" con una función para crearlos, va a poder hacer algo más? Mira el hito en el que está incluida, un "sistema". Si te entrega una web que tiene un formulario que dice "nombre de cajón" y al meter algo te dice "creado cajón" ¿se alcanzará ese producto? Por favor, no os quedéis con la letra de lo que escribís. Tratad de entender la música (los conceptos que hay detrás).

Pero si no hago una clase cajones, no existirían en la aplicación. Con esta historia de usuario el susodicho crea el cajón. Lo que en la clase sería crear el objeto (constructor) y todos los métodos de los que disponga dicha clase. De ahí que lo englobe en el hito de gestión de cajones (lo que yo entiendo como la clase en la que se llevarán a cabo las acciones que podrá realizar el objeto cahón)

2021-09-29 05:02 UTC, JJ commented
Permíteme que señale un par de claves en lo que dices. "Todos los métodos que disponga" debería decir específicamente cuales son esos métodos y qué logica de negocio tienen. "Lo que yo entiendo" no es lo que tiene que haber en una planificación. Debe entenderla cualquiera, como te he dicho.

2021-09-29 14:33 UTC, lentes4k commented
Es que en este caso se puede decir que "tengo un problema"
Es obvio que una historia de usuario es la de crear cajones, puesto que como usuario quiero crear el cajón para poder guardar dentro cosas.
Entiendo que un producto tiene que llevar lógica de negocio. Pero la lógica principal de la aplicación está en el almacenamiento automático de las notas.
Por lo tanto a la hora de crear los cajones, su clase sería el constructor y llevaría una serie de parámetros para saber si ese cajón pertenece a otro, si tiene subcajones. Los típicos modificadores para modificar cosas, tipo cambiar nombre, añadir notas a la "lista" (o contenedor que use). Los aún más típicos consultores para ver ciertos parámetros fuera de la clase. 
Al final creo que la clase cajones es necesaria pero no hay manera de aportar lógica de negocio. Toda la lógica la recibirá la clase "nota" con métodos que analicen el texto introducido por el usuario para seleccionar el cajón adecuado y para almacenar palabras más usadas.
Quizás la única lógica de negocio que se me ocurre para la clase "cajones" sea la de tratamiento para ver que cajones son los más usados por los usuarios con el fin de implementar mejoras en ese sector (ej: la mayoría lo usan como lista de compra, implementar autocompletado de productos, posibilidad de recordar al usuario que tiene que hacerla...) o vender esos datos.

2021-09-29 15:11 UTC, JJ commented
> Es que en este caso se puede decir que "tengo un problema" Es obvio que una historia de usuario es la de crear cajones, puesto que como usuario quiero crear el cajón para poder guardar dentro cosas. Entiendo que un producto tiene que llevar lógica de negocio. Pero la lógica principal de la aplicación está en el almacenamiento automático de las notas. Por lo tanto a la 

Entonces no tiene lógica de negocio. Almacenar no es lógica de negocio, Por favor, mira el tutorial sobre el tema.

> hora de crear los cajones, su clase sería el constructor y llevaría una serie de parámetros para saber si ese cajón pertenece a otro, si tiene subcajones. Los típicos modificadores para modificar cosas, tipo cambiar nombre, añadir notas a la "lista" (o contenedor que use). Los aún más típicos consultores para ver ciertos parámetros fuera de la clase. Al final creo que la clase cajones es necesaria pero no hay manera de aportar lógica de negocio. Toda la lógica la recibirá la clase "nota" con métodos 

No tiene que haber lógica de negocio en cada clase. Y el que lo coloques en una u otra es arbitrario. Si lo que quieres es aplicar "notas" a "cajones", dónde la coloques da igual. Las notas tienen que acabae en los cajones.


> que analicen el texto introducido por el usuario para seleccionar el cajón adecuado y para almacenar palabras más usadas. Quizás la única lógica de negocio que se me ocurre para la clase "cajones" sea la de tratamiento para ver que cajones son los más usados por los usuarios con el fin de implementar mejoras en ese sector (ej: la mayoría lo usan como lista de compra, 

Mira, es una idea interesante. Pero la que tenías adicionalmente también lo era. Lo que tienes que pensar es como pasar de una idea a las órdenes y fases de implementación.

2021-09-30 07:53 UTC, lentes4k commented
JJ, le he vuelto a dar una vueltecita

2021-09-30 15:23 UTC, JJ approved these changes
Ha avanzado bastante, como hemos hablado, y yo creo que el objetivo está alcanzado, enhorabuena. Pero
* Cuida los errores como "detención"
* Clarifica qué "sistema" vas a usar. Recuerda que le va a tocar a otra persona.

2021-09-30 15:23 UTC, JJ commented on docs/usuarios.md
> +Si bien es cierto que, como explico más adelante se cogerán una serie de datos con el finde de implementar mejores en aquellos *cajones* más usados o las funciones que el usuario use más
typo: finde

2021-09-30 18:29 UTC, lentes4k commented
Okey, profe. Le doy una revisión a las erratas.
Me podrías también orientar un poco sobre la pregunta de mi anterior comentario?
Gracias!

2021-10-01 05:53 UTC, JJ commented
> Okey, profe. Le doy una revisión a las erratas. Me podrías también orientar un poco sobre la pregunta de mi anterior comentario? Gracias!

Lo mejor es que hagas las cosas y lo marques para revisión; es difícil buscar entre las preguntas lo que quieres decir. haz también lo que hablamos en clase, que entiendo que es más o menos lo que preguntas.

2021-10-01 10:51 UTC, lentes4k commented
> > Okey, profe. Le doy una revisión a las erratas. Me podrías también orientar un poco sobre la pregunta de mi anterior comentario? Gracias!
> 
> Lo mejor es que hagas las cosas y lo marques para revisión; es difícil buscar entre las preguntas lo que quieres decir. haz también lo que hablamos en clase, que entiendo que es más o menos lo que preguntas.

Lo he hecho, así que cuando puedas le echas un ojillo y me dices si lo he expresado correctamente y ya procederé con el "mergeo"
Gracias!

2021-10-01 15:12 UTC, JJ approved these changes
Lo considero superado, aunque todavía no has clarificado qué tipo de "sistema" buscas como los diferentes PMVs, y tampoco tienes un hito 0 que será necesario. Te tocará aclararlo en el siguiente hito, que hará otra persona, en este caso @paszser

2021-10-01 15:14 UTC, JJ commented
(vale, y ya lo había aprobado ayer...)

2021-10-04 14:07 UTC, merged