Renuevo la idea para cumplir requisitos del hito 0
lentes4k/Proyecto-IV pull request #2
Opened 2021-09-21 16:37 UTC by lentes4k

2021-09-21 17:51 UTC, JJ requested changes
Estás muy cerca, por favor dale una pequeña vuelta.

2021-09-21 17:51 UTC, JJ commented on README.md
> +# cAppjón de sastre
El nombre es la caña. :100:

2021-09-21 17:51 UTC, JJ commented on README.md
> +Es por esta razón por la que aparece *cAppjón de sastre*, el bot que al mandar el mensaje, añadiendo un tag al inicio del mismo la añadirá al *cajón* correspondiente, con la posibilidad de almacenar
Potencialmente, esto puede ser simplemente un sistema de "almacena y busca", que *no* es lo que buscamos en la clase. Parece que implícitamente se va a analizar la información para saber a qué cajón va, pero no queda nada claro. Por otro lado, tienes todavía algún typo. Si corriges esas dos cosas, podrá ser aceptado (pero espérate a que lo haga explícitametne para fusionar)

2021-09-22 09:20 UTC, lentes4k commented on README.md
> +Es por esta razón por la que aparece *cAppjón de sastre*, el bot que al mandar el mensaje, añadiendo un tag al inicio del mismo la añadirá al *cajón* correspondiente, con la posibilidad de almacenar
Había pensado incluso permitir detención de palabras en los mensajes para automatizar la inclusión en los diferentes cajones. Además de la posibilidad de crear los cajones, cajones anidados y otras cosas tipo al mandar el mensaje que se borre del chat para que no se quede ocupando espacio (si se pudiera, que no lo sé) o permitir que algunas de esas anotaciones tengan recordatorios.
Pero claro, si incluyo todo esto me queda una descripción muy amplia como presentación del proyecto, ¿no?

2021-09-22 11:17 UTC, JJ commented on README.md
> +Es por esta razón por la que aparece *cAppjón de sastre*, el bot que al mandar el mensaje, añadiendo un tag al inicio del mismo la añadirá al *cajón* correspondiente, con la posibilidad de almacenar
A ver, la parte de "cajones" es implementación (porque el usuario no tiene que preocuparse de eso), pero no está demás que lo incluyas como aclaración de que efectivamente hay una cierta lógica de negocio detrás.

2021-09-22 11:32 UTC, lentes4k commented on README.md
> +Es por esta razón por la que aparece *cAppjón de sastre*, el bot que al mandar el mensaje, añadiendo un tag al inicio del mismo la añadirá al *cajón* correspondiente, con la posibilidad de almacenar
Ya creo que he aportado algo más de lógica de negocio. No estaba familiarizado con el concepto y no sé si lo he hecho de forma correcta

2021-09-22 11:36 UTC, JJ approved these changes
:takeout_box:

2021-09-22 11:36 UTC, JJ commented on README.md
> +Es por esta razón por la que aparece *cAppjón de sastre*, el bot que al mandar el mensaje, añadiendo un tag al inicio del mismo la añadirá al *cajón* correspondiente, que podrás crear con anteriorida
Como dices en tu comentario, la parte de "automatizar" es importante, pero no la has mencionado aquí. Entiendo de todas formas que has superado el objetivo, pero por favor ten en cuenta que en el estado que está ahora mismo sería sólo "almacena y busca". Cuando trabajes en el objetivo siguiente recuerda que la automatización será parte fundamental.

2021-09-22 14:00 UTC, lentes4k commented on README.md
> +Es por esta razón por la que aparece *cAppjón de sastre*, el bot que al mandar el mensaje, añadiendo un tag al inicio del mismo la añadirá al *cajón* correspondiente, que podrás crear con anteriorida
Okey, gracias profe!

2021-09-22 14:04 UTC, merged